# docker-compose.yml
version: '3.8'

services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./storage:/var/www/html/storage
            - ./.env:/var/www/html/.env
        depends_on:
            - mysql
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
