# docker-compose.yml
version: '3.8'

services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./storage:/var/www/html/storage
            - ./.env:/var/www/html/.env
        depends_on:
            - mysql
        environment:
            - APP_ENV=production
            - APP_DEBUG=false

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bartho
            MYSQL_USER: bartho_user
            MYSQL_PASSWORD: bartho_password
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mysql

volumes:
    mysql_data:
